In [2]:
import pandas as pd 
from scipy import stats
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from scipy.spatial import distance


In [3]:
df = pd.read_csv("aps_failure_training_set.csv") 
df_train = pd.read_csv("aps_failure_test_set.csv")
#print(df.shape)


df = df.rename(columns = {'class' : 'Flag'})
df['Flag'] = df.Flag.map({'neg':0, 'pos':1})
df = df.replace(['na'],[np.NaN])
#print(df.head())


df_X= df.loc[:,df.columns != 'Flag']
df_Y= df.loc[:,df.columns == 'Flag']
df_X=df_X.apply(pd.to_numeric)
df_Y=df_Y.apply(pd.to_numeric)


df_train = df_train.rename(columns = {'class' : 'Flag'})
df_train['Flag'] = df_train.Flag.map({'neg':0, 'pos':1})
df_train = df_train.replace(['na'],[np.NaN])


df_train_X= df_train.loc[:,df.columns != 'Flag']
df_train_Y= df_train.loc[:,df.columns == 'Flag']
#print(df_train_Y)
df_train_X=df_train_X.apply(pd.to_numeric)
df_train_Y=df_train_Y.apply(pd.to_numeric)


In [4]:
df_Y

Flag
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         1
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        1
24        0
25        0
26        0
27        0
28        0
29        0
...     ...
59970     0
59971     0
59972     0
59973     0
59974     0
59975     0
59976     0
59977     0
59978     0
59979     0
59980     0
59981     0
59982     0
59983     0
59984     0
59985     0
59986     0
59987     0
59988     0
59989     0
59990     0
59991     0
59992     0
59993     0
59994     0
59995     0
59996     0
59997     0
59998     0
59999     0

[60000 rows x 1 columns]

In [5]:
for columns in df_X:
    df_Z=df_X.loc[abs(df_X[columns]-df_X[columns].mean())<=(3 * df_X[columns].std())]
    (a,b)=(df_Z.shape)
    if a <=55000:
        del df_X[columns]
print(df_X.head())
  
col=list(df_X)
df_train_X=df_train_X[col]
print(df_train_X.head())    

df_X=df_X.fillna(df_X.mean()).dropna(axis=1, how='all')
# """scaler = StandardScaler()

# scaler.fit(df_X)

# df_X = scaler.transform(df_X)

# pca = PCA(0.98)

# pca.fit(df_X)

# print(pca.n_components_)

# df_X = pca.transform(df_X)

# df_X= pd.DataFrame(df_X)
# """
df_train_X=df_train_X.fillna(df_train_X.mean()).dropna(axis=1, how='all')
# """
# scaler = StandardScaler()

# scaler.fit(df_train_X)

# df_train_X = scaler.transform(df_train_X)

# pca = PCA(86)

# pca.fit(df_train_X)

# print(pca.n_components_)

# df_train_X = pca.transform(df_train_X)

# df_train_X= pd.DataFrame(df_train_X)


   aa_000        ac_000  ae_000  af_000  ag_000  ag_001  ag_002  ag_003  \
0   76698  2.130706e+09     0.0     0.0     0.0     0.0     0.0     0.0   
1   33058  0.000000e+00     0.0     0.0     0.0     0.0     0.0     0.0   
2   41040  2.280000e+02     0.0     0.0     0.0     0.0     0.0     0.0   
3      12  7.000000e+01     0.0    10.0     0.0     0.0     0.0   318.0   
4   60874  1.368000e+03     0.0     0.0     0.0     0.0     0.0     0.0   

    ag_004     ag_005   ...       ee_002    ee_003    ee_004    ee_005  \
0  37250.0  1432864.0   ...    1240520.0  493384.0  721044.0  469792.0   
1  18254.0   653294.0   ...     421400.0  178064.0  293306.0  245416.0   
2   1648.0   370592.0   ...     277378.0  159812.0  423992.0  409564.0   
3   2212.0     3232.0   ...        240.0      46.0      58.0      44.0   
4  43752.0  1966618.0   ...     622012.0  229790.0  405298.0  347188.0   

     ee_006    ee_007    ee_008  ee_009  ef_000  eg_000  
0  339156.0  157956.0   73224.0     0.0     0.

In [6]:
from sklearn.neighbors import KNeighborsClassifier
## Instantiate the model with 5 neighbors. 
knn = KNeighborsClassifier(n_neighbors=150)
## Fit the model on the training data.
knn.fit(df_X, df_Y.values.ravel())
## See how the model performs on the test data.
Y_pred=knn.predict(df_train_X)
print(confusion_matrix(df_train_Y.values.ravel(),Y_pred))



#print(df_X.head())
#df_X[(np.abs(stats.zscore(df_X)) < 3).all(axis=1)]
#print(df_X)
#print(df_X["aa_000"]-df_X["aa_000"].mean())
#print(df_X.ix[:,0]-df_X.ix[:,0].mean())
#print(df_X["aa_000"])

#df_X=df_X[np.abs(df_X.aa_000-df_X.aa_000.mean()) <= (3*df_X.aa_000.std())]
#df_X=df_X[np.abs(df_X.ab_000-df_X.ab_000.mean()) <= (3*df_X.ab_000.std())]
#df_X=df_X[np.abs(df_X.ac_000-df_X.ac_000.mean()) <= (3*df_X.ac_000.std())]


[[15615    10]
 [  352    23]]


In [7]:
distances=(distance.cdist(df_train_X,df_X))
print(np.shape(distances))


(16000, 60000)


In [8]:

predicted_label = []
for i in range (0,16000) :
    sorted_distances=np.argsort(distances[i,:])
    v=sorted_distances[:500]
    temp_output = []
    for index in v:
        if df_Y.iloc[index]["Flag"] == 1:
            temp_output.append(1)
            if len(temp_output) == 3:
                break
    if len(temp_output) == 3:
        predicted_label.append(1)
    else:
        predicted_label.append(0)

print(confusion_matrix(df_train_Y.values.ravel(),predicted_label))   
    

[[14452  1173]
 [    6   369]]


In [9]:
predicted_label = []
for i in range (0,16000) :
    sorted_distances=np.argsort(distances[i,:])
    v=sorted_distances[:600]
    temp_output = []
    for index in v:
        if df_Y.iloc[index]["Flag"] == 1:
            temp_output.append(1)
            if len(temp_output) == 3:
                break
    if len(temp_output) == 3:
        predicted_label.append(1)
    else:
        predicted_label.append(0)

print(confusion_matrix(df_train_Y.values.ravel(),predicted_label))   
    

[[14358  1267]
 [    6   369]]
